# Theme: Matrix Hacker
# By: JSobarzo

# Main bg
theme[main_bg]="#000000"

# Main text color
theme[main_fg]="#22b455"

# Title color for boxes
theme[title]="#22b455"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#00cc77"

# Background color of selected item in processes box
theme[selected_bg]="#00cc77"

# Foreground color of selected item in processes box
theme[selected_fg]="#ccffee"

# Color of inactive/disabled text
theme[inactive_fg]="#1a1a1a"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#22b455"

# Cpu box outline color
theme[cpu_box]="#00cc77"

# Memory/disks box outline color
theme[mem_box]="#00cc77"

# Net up/down box outline color
theme[net_box]="#00cc77"

# Processes box outline color
theme[proc_box]="#00cc77"

# Box divider line and small boxes line color
theme[div_line]="#00cc77"

# Temperature graph colors
theme[temp_start]="#22b455"
theme[temp_mid]="#00cc77"
theme[temp_end]="#ccffee"

# CPU graph colors
theme[cpu_start]="#22b455"
theme[cpu_mid]="#00cc77"
theme[cpu_end]="#ccffee"

# Mem/Disk free meter
theme[free_start]="#22b455"
theme[free_mid]="#00cc77"
theme[free_end]="#ccffee"

# Mem/Disk cached meter
theme[cached_start]="#22b455"
theme[cached_mid]="#00cc77"
theme[cached_end]="#ccffee"

# Mem/Disk available meter
theme[available_start]="#22b455"
theme[available_mid]="#00cc77"
theme[available_end]="#ccffee"

# Mem/Disk used meter
theme[used_start]="#22b455"
theme[used_mid]="#00cc77"
theme[used_end]="#ccffee"

# Download graph colors
theme[download_start]="#22b455"
theme[download_mid]="#00cc77"
theme[download_end]="#ccffee"

# Upload graph colors
theme[upload_start]="#22b455"
theme[upload_mid]="#00cc77"
theme[upload_end]="#ccffee"


