return {
	{
		"LazyVim/LazyVim",
		opts = {
			colorscheme = "catppuccin",
		},
	},
	{
		"catppuccin/nvim",
		name = "catppuccin",
		opts = {
			flavour = "mocha",
			background = {
				light = "latte",
				dark = "mocha",
			},
			transparent_background = false,
			term_colors = true,
			dim_inactive = {
				enabled = false,
				shade = "dark",
				percentage = 0.15,
			},
			styles = {
				comments = { "italic" },
				conditionals = { "italic" },
				loops = {},
				functions = {},
				keywords = {},
				strings = {},
				variables = {},
				numbers = {},
				booleans = {},
				properties = {},
				types = {},
				operators = {},
			},
			integrations = {
				-- For various plugins
				cmp = true,
				gitsigns = true,
				nvimtree = true,
				telescope = true,
				notify = true,
				mini = false,
			},
			color_overrides = {
				mocha = {
					base = "#000000",
					mantle = "#0a0a0a",
					crust = "#000000",
					text = "#ccffee",
					subtext0 = "#888888",
					subtext1 = "#aaaaaa",
					overlay0 = "#111111",
					overlay1 = "#1a1a1a",
					overlay2 = "#333333",
					surface0 = "#0a0a0a",
					surface1 = "#111111",
					surface2 = "#1a1a1a",
					blue = "#00aaff",
					lavender = "#00ffcc",
					sapphire = "#00ddff",
					sky = "#00ffee",
					teal = "#00cc77",
					green = "#00ff99",
					yellow = "#ffff00",
					peach = "#ffaa00",
					maroon = "#ff6666",
					red = "#ff3333",
					mauve = "#cc99ff",
					pink = "#ff99cc",
					flamingo = "#ffccaa",
					rosewater = "#ccffee",
				},
			},
		},
	},
}
